version: 2
jobs:

  build:

    docker:
      - image: luongbui/debian_stretch_docker:17.05.0-ce

    environment:
      DOCKER_REPO: "luongbui/dart-vm_armv6"
      TAG: "2.0.0-dev.55.0"

    steps:

      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image with dart-vm binary
          command: |
            docker build  --build-arg dart_version=$TAG --tag $DOCKER_REPO:$TAG .

      - run:
          name: Upload Docker image to Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_REPO:$TAG

      - run:
          name: Copy /dart-sdk.zip to /tmp/
          command: |
            CONTAINER_ID=$(docker create $DOCKER_REPO:$TAG)
            docker cp $CONTAINER_ID:/dart-sdk.zip /tmp/dart-sdk.zip

      - store_artifacts:
          path: /tmp/dart-sdk.zip
          destination: binaries

